# Generated by Django 6.0.4 on 2026-04-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=127)),
                ('email', models.EmailField(max_length=254)),
                ('assunto', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('data', models.DateTimeField()),
            ],
        ),
    ]
