# Generated by Django 6.0.4 on 2026-04-17 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_contato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='data',
        ),
    ]
